### ISSUE TITLE
Mention build requirements

### ISSUE THREAD

**Issue by jserv** [champyen/cltk#1]
The current build system lacks of the ability to verify host build environments, which are expected to satisfy the OpenCL dependency. It would be great if `README.md` mentions the dependent packages or instructions to build `cltk`.

**Comment by champyen** [comment]
Currently the major infrastructure of CLTK is still under development.
After then, I will create a better build environment with CMake and give a clear guide for library build.

**Comment by champyen** [comment]
I have updated simple build guide.
OpenCL runtime setup information is added.

**Comment by jserv** [comment]
@champyen, Great work! Thanks.
