### ISSUE TITLE
Adapt 2-clause BSD license

### ISSUE THREAD

**Issue by jserv** [champyen/cltk#3]
At present, `cltk` is licensed under 3-clause BSD license, which contains non-endorsement clause. To be compatible with GNU GPL v2, several projects such as FreeBSD already migrate to 2-clause license as known as "Simplified BSD License" or "FreeBSD License".

Would you consider to re-license to adapt 2-clause BSD license?

Reference: https://en.wikipedia.org/wiki/BSD_licenses

**Comment by champyen** [comment]
ok, It is done.
